# Generated by Django 4.2 on 2023-11-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_name', models.CharField(max_length=30)),
                ('influencer_phone', models.IntegerField()),
                ('influencer_email', models.EmailField(max_length=254)),
                ('influencer_code', models.TextField(max_length=10)),
                ('password', models.TextField()),
            ],
        ),
    ]
