# Generated by Django 4.2 on 2023-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_influencerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='influencerinstagram',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='influencername',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
