# Generated by Django 4.2 on 2023-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission',
            field=models.IntegerField(null=True),
        ),
    ]
