# Generated by Django 4.2 on 2023-12-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_newuser_managers_remove_newuser_username_and_more'),
    ]

    operations = [
       
       
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True),
        ),
       
    ]
