# Generated by Django 4.2 on 2023-12-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_newuser_managers_remove_newuser_username_and_more'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='orderplaced',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow')], max_length=255, null=True),
        ),
       
    ]
