# Generated by Django 4.2 on 2023-12-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_newuser_managers_remove_newuser_username_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=40, null=True),
        ),
        
    ]
