# Generated by Django 4.2 on 2023-12-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_newuser_managers_remove_newuser_username_and_more'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
      
        migrations.RemoveField(
            model_name='orderplaced',
            name='size',
        ),
      
    ]
