# Generated by Django 4.2 on 2023-12-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_newuser_managers_remove_cart_size_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=40, null=True),
        ),
     
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=40, null=True),
        ),
    ]
