# Generated by Django 4.2 on 2023-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_newuser_managers_remove_newuser_username_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='orderplaced',
            name='customer_info',
            field=models.CharField(max_length=255, null=True),
        ),
     
    ]
