# Generated by Django 4.2 on 2023-12-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_newuser_managers_remove_newuser_username_and_more'),
    ]

    operations = [
     
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer_info',
        ),
       
    ]
