# Generated by Django 4.2 on 2023-12-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_newuser_managers_remove_newuser_username_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='orderplaced',
            name='influencercode',
            field=models.TextField(max_length=10, null=True),
        ),
       
    ]
