# Generated by Django 4.2 on 2024-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_newuser_managers_remove_newuser_username_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
