# Generated by Django 4.2 on 2024-01-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_newuser_managers_alter_newuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='color',
            field=models.CharField(choices=[('N', 'None'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('N', 'None'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='color',
            field=models.CharField(choices=[('N', 'None'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='size',
            field=models.CharField(choices=[('N', 'None'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('N', 'None'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('N', 'None'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=40, null=True),
        ),
    ]
