# Generated by Django 4.2 on 2024-01-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_color_size_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T', 'T-shirts'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('MTH', 'Mens T-Shirts and Hoodies'), ('MSC', 'Mens Shirts & Coats'), ('MPS', 'Mens Pants & Shorts'), ('MSI', 'Mens Sportswear and innerwear'), ('MTT', 'Mens Tamil Traditional wears'), ('GTTS', 'Girls Tops, T-Shirts & Shirts'), ('GJP', 'Girl Jeans & Pants'), ('GSS', 'Girls Skirts & Shorts'), ('GSI', 'Girls Sportswear and innerwear'), ('GS', 'Girls Sleepwear'), ('GTS', 'Girls Tights & Leggings'), ('GTT', 'womens Tamil Traditional wears'), ('b1', 'boy(0-1)'), ('b2', 'boy(1-2)'), ('b3', 'boy(3 or 3+)'), ('g1', 'girl(0-1)'), ('g2', 'girl(1-2)'), ('g3', 'girl(3 or 3+)')], max_length=20),
        ),
    ]
