# Generated by Django 4.2 on 2024-01-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_product_product_image2_product_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='save_entry',
            field=models.BooleanField(default=False),
        ),
    ]
