# Generated by Django 4.2 on 2024-01-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_product_save_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='save_entry',
            field=models.BooleanField(default=True),
        ),
    ]
