# Generated by Django 4.2 on 2024-01-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_product_save_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('T', 'T-shirts'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('MTH', 'Mens T-Shirts and Hoodies'), ('MSC', 'Mens Shirts & Coats'), ('MPS', 'Mens Pants & Shorts'), ('MSI', 'Mens Sportswear and innerwear'), ('MTT', 'Mens Tamil Traditional wears'), ('GTTS', 'Girls Tops, T-Shirts & Shirts'), ('GJP', 'Girl Jeans & Pants'), ('GSS', 'Girls Skirts & Shorts'), ('GSI', 'Girls Sportswear and innerwear'), ('GS', 'Girls Sleepwear'), ('GTS', 'Girls Tights & Leggings'), ('GTT', 'womens Tamil Traditional wears'), ('b1', 'boy(0-1)'), ('b2', 'boy(1-2)'), ('b3', 'boy(3 or 3+)'), ('g1', 'girl(0-1)'), ('g2', 'girl(1-2)'), ('g3', 'girl(3 or 3+)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='commission',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='factory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='producting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='app.size'),
        ),
    ]
