# Generated by Django 4.2 on 2024-02-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(blank=True, default='producting/not.png', null=True, upload_to='producting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(blank=True, default='producting/not.png', null=True, upload_to='producting'),
        ),
    ]
